[package]
name = "mini-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
mini-sync-common = { path = "../mini-sync-common" }
qrcode = "0.14.1"
rand = "0.8.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
